# Generated by Django 4.2.1 on 2023-05-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('images', models.ImageField(upload_to='img')),
                ('link', models.URLField(verbose_name='Link')),
                ('review', models.IntegerField()),
            ],
        ),
    ]
